cart/urls.py
from django.urls import path
from . import views
from .views import OrderCreate

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', OrderCreate.as_view(), name='order'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls,),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.utils.translation import gettext as _


class Order(models.Model):
    first_name = models.CharField(_('Имя'), max_length=50)
    last_name = models.CharField(_('Фамилия'), max_length=50)
    email = models.EmailField(_('Электронная почта'),)
    address = models.CharField(_('Адрес'), max_length=150)
    date = models.DateField(_('Дата доставки'))
    number = models.BigIntegerField(_('Номер телефона получателя'), blank=True, null=True)
    comments = models.CharField(_('Комментарий'), max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f"{self.first_name}-{self.last_name}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

main/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse


class Category(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50)
    title = models.CharField(max_length=50,)
    parent = models.ForeignKey('self', related_name='children', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        if self.parent:
            return f'{self.parent} -> {self.title}'
        return self.title

    @property
    def get_children(self):
        if self.children:
            return self.children.all()
        return False


class Product(models.Model):
    STATUS_CHOICES = (
        ('in stock', 'В наличии'),
        ('out of stock', 'Нет в наличии')
    )

    title = models.CharField(max_length=50,)
    category = models.ManyToManyField(Category, related_name='products',)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/')
    price = models.DecimalField(max_digits=12, decimal_places=2)
    stock = models.CharField(choices=STATUS_CHOICES, max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    @property
    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    def get_category_name(self):
        return self.category

    class Meta:
        ordering = ['-created']

cart/forms.py
from django import forms

from cart.models import Order

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs = {
            'placeholder': 'Введите ваше имя',
            'class': 'form-control',
            'required': True
        }
        self.fields['last_name'].widget.attrs = {
            'placeholder': 'Введите вашу фамилию',
            'class': 'form-control',
            'required': True
        }
        self.fields['email'].widget.attrs = {
            'placeholder': 'Введите вашу почту',
            'class': 'form-control',
            'required': True
        }
        self.fields['address'].widget.attrs = {
            'placeholder': 'Улица, дом и номер квартиры',
            'class': 'form-control',
            'required': True
        }

        self.fields['number'].widget.attrs = {
            'placeholder': 'Ваш номер телефона',
            'class': 'form-control',
            'required': False
        }
        self.fields['date'].widget.attrs = {
            'placeholder': 'Выберите дату доставки',
            'class': 'form-control',
            'required': False
        }

        self.fields['comments'].widget.attrs = {
            'placeholder': 'Есть комментарии к заказу??',
            'class': 'form-control',
            'required': False
        }

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address', 'number',
                  'date', 'comments', )
        widgets = {
            'date': forms.DateInput(format=('%m/%d/%Y'),
                                    attrs={'class': 'form-control', 'placeholder': 'Дата доставки','type': 'date'}),
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.context_processors import request
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from main.models import Product
from main.task import send_beat_email, send_spam_email
from shop import settings
from .cart import Cart
from .forms import CartAddProductForm, OrderForm
from django.core.mail import send_mail
from django.views.generic import CreateView

from .models import Order


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart.html', {'cart': cart})


class OrderCreate(CreateView):
    model = Order
    template_name = 'order.html'
    form_class = OrderForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        product = form.save(commit=False)
        product.save()
        email = 'johnsnowtest73@gmail.com'
        send_spam_email.delay(email)
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>

    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

</head>
<body>
    
    <header id="header">

        <div id="nav-content">
            <a href="{% url 'home' %}" class="logo">HikingShop</a>
    
            <form method="get" action="#">
                <input type="text" name="query" id="query" placeholder="Search...">
            </form>
    
            <ul>
                {% if request.user.is_superuser %}
                <li><a href="http://localhost:8000/admin/">Админ</a></li>
                {% endif %}

                <li><a href="{% url 'category' rent.slug %}">Прокат</a></li>
                <li><a href="{% url 'catalog' %}">{{ shop }}</a></li>
                <li><a href="http://localhost:8000/cart/">Корзина</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Войти</a></li>
                {% else %}
                    <li><a href="{% url 'logout' %}">{{ request.user.username }}</a></li>
                {% endif %}
            </ul>
        </div>

        <div id="nav-menu">
            <form method="get" action="#">
                <input type="text" name="query" placeholder="Search...">
            </form>
            <ul>
                {% if request.user.is_superuser %}
                <li><a href="http://localhost:8000/admin/">Админ</a></li>
                {% endif %}

                <li><a href="{% url 'category' rent.slug %}">Прокат</a></li>
                <li><a href="{% url 'catalog' %}">{{ shop }}</a></li>
                <li><a href="http://localhost:8000/cart/">Корзина</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Войти</a></li>
                {% else %}
                    <li><a href="{% url 'logout' %}">{{ request.user.username }}<i class="fa fa-sign-out" style="font-size:36px"></i></a></li>
                {% endif %}
            </ul>
        </div>

        <img id="burger-menu" src="{% static 'images/burger-menu.svg' %}" alt="burger-menu">

    </header>

    {% block content %}{% endblock %}
    
    <footer id="footer">
        <div class="footer-content">
            <div class="contacts">
                <h4>Наши контакты</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
                <p>4</p>
                <p>5</p>
            </div>
            <div class="schedule">
                <h4>График работы</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
            <div class="socials">
                <h4>Социальные сети</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
        </div>
    </footer>


    <script>
        let menuClicked = false;

        const burger_menu = document.getElementById("burger-menu");

        const nav_menu = document.getElementById("nav-menu");

        burger_menu.addEventListener("click", () => {
        if (menuClicked) {
          nav_menu.style.marginRight = "-170px";
          nav_menu.style.display = "none";
        } else {
          nav_menu.style.marginRight = 0;
          nav_menu.style.display = "block";
        }
        menuClicked = !menuClicked;
      });
    </script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="cart_section" style="margin-bottom: 25px;">

        <div class="cart">

            <div class="conditions">
                <p>Товар</p>
                <p>Количество</p>
                <p>Стоимость</p>
            </div>
            {% for item in cart %}
            {% with product=item.product %}
            <div class="cart_product">

                <p>{{ product.title }}</p>
                <form action="{% url 'cart:cart_add' product.id %}" style="position: absolute; margin-left: 330px;" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить" style="width: 110px; background: #fff; color: #094b65; border-radius: 40px;">
                {% csrf_token %}
                </form>
                <p>{{ item.price }}</p>
                <a href="{% url 'cart:cart_remove' product.id %}" style="position: absolute; margin-left: 600px; text-decoration: none; color: #DC143C;">Удалить</a></td>

            </div>
            {% endwith %}
            {% endfor %}


            <h2>Итого: {{ cart.get_total_price }}</h2>
            <a href="http://localhost:8000/cart/order/"><button>Оформить заказ</button></a>

        </div>

    </div>

{% endblock %}

templates/catalog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="catalog">

        <div class="catalog-content">
            <div class="catalog-filter" style="max-height: 300px!important;">
                <h3>{{ shop.title }}</h3>

                <ul class="list-group">
                    {% for child in shop.get_children %}
                    <a href="{% url 'category' child.slug %}" style="text-decoration: none;"><li class="list-group-item">{{ child.title }}</li></a>
                    {% endfor %}
                </ul>
            </div>

            <div class="cards">
                {% for product in page_obj %}
                <div class="card">
                    <img src="{{ product.image.url }}" alt="photo">
                    <h3>{{ product }}</h3>
                    <p>{{ product.price }}</p>
                    <a href="{% url 'detail' product.id %}">
                        <button>Подробнее</button>
                    </a>
                </div>
                {% endfor %}


                <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
           {% if not page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Назад</a>
        </li>
          {% else %}
          <li class="page-item">
          <a class="page-link" href="{% url 'catalog' %}?page={{ page_obj.previous_page_number }}">Назад</a>
        </li>
          {% endif %}

          {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'catalog' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
        {% endif %}

          <li class="page-item active"><a class="page-link" href="#">{{  page_obj.number }}</a></li>

          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="{% url 'catalog' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
          {% endif %}

          {% if not page_obj.has_next %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Вперед</a>
        </li>
          {% else %}
          <li class="page-item">
          <a class="page-link" href="{% url 'catalog' %}?page={{ page_obj.next_page_number }}">Вперед</a>
        </li>
          {% endif %}
      </ul>
    </nav>
            </div>

        </div>
    </div>
{% endblock %}

templates/category_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="catalog">

        <div class="catalog-content">
            {% if not category.parent %}
            <div class="catalog-filter" style="max-height: 300px!important;">
                <h3>{{ category.title }}</h3>

                <ul class="list-group">
                    {% for child in category.get_children %}
                    <a href="{% url 'category' child.slug %}" style="text-decoration: none;"><li class="list-group-item">{{ child.title }}</li></a>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% if category.parent %}
            <div class="catalog-filter" style="height: 280px!important; margin-bottom: 30px;">
                <h3>{{ category.parent.title }}</h3>

                <ul class="list-group">
                    {% for child in category.parent.get_children %}
                    <a href="{% url 'category' child.slug %}" style="text-decoration: none;"><li class="list-group-item">{{ child.title }}</li></a>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="cards">
                {% for product in products %}
                <div class="card">
                    <img src="{{ product.image.url }}" alt="photo">
                    <h3>{{ product }}</h3>
                    <p>{{ product.price }}</p>
                    <a href="{% url 'detail' product.id %}">
                        <button>Подробнее</button>
                    </a>
                </div>
                {% endfor %}

<!--                <nav aria-label="Page navigation example">-->
<!--      <ul class="pagination justify-content-center">-->
<!--           {% if not products.has_previous %}-->
<!--        <li class="page-item disabled">-->
<!--          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>-->
<!--        </li>-->
<!--          {% else %}-->
<!--          <li class="page-item">-->
<!--          <a class="page-link" href="#">Назад</a>-->
<!--        </li>-->
<!--          {% endif %}-->
<!--    	  {% if products.has_previous %}-->
<!--        <li class="page-item"><a class="page-link" href="#">products.previous_page_number</a></li>-->
<!--        {% endif %}-->
<!--          <li class="page-item active"><a class="page-link">{{  products.number }}</a></li>-->
<!--        {% if products.has_next %}-->
<!--          <li class="page-item"><a class="page-link" href="#">{{ products.next_page_number }}</a></li>-->
<!--        <li class="page-item">-->
<!--            {% endif %}-->
<!--          <a class="page-link" href="#">Вперед</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </nav>-->
            </div>

        </div>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hiking Shop</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
    <header id="header">

        <div id="nav-content">
            <a href="{% url 'home' %}" class="logo">HikingShop</a>
    
            <form method="get" action="#">
                <input type="text" name="query" id="query" placeholder="Search...">
            </form>
    
            <ul>
                {% if request.user.is_superuser %}
                <li><a href="http://localhost:8000/admin/">Админ</a></li>
                {% endif %}

                <li><a href="{% url 'category' rent.slug %}">Прокат</a></li>
                <li><a href="{% url 'catalog' %}">{{ shop }}</a></li>
                <li><a href="http://localhost:8000/cart/">Корзина</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Войти</a></li>
                {% else %}
                    <li><a href="{% url 'logout' %}">{{ request.user.username }}</a></li>
                {% endif %}
            </ul>
        </div>

        <div id="nav-menu">
            <form method="get" action="{% url 'home' %}">
                <input type="text" name="query" placeholder="Search...">
            </form>
            <ul>
                {% if request.user.is_superuser %}
                <li><a href="http://localhost:8000/admin/">Админ</a></li>
                {% endif %}

                <li><a href="{% url 'category' rent.slug %}">Прокат</a></li>
                <li><a href="{% url 'catalog' %}">{{ shop }}</a></li>
                <li><a href="http://localhost:8000/cart/">Корзина</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Войти</a></li>
                {% else %}
                    <li><a href="{% url 'logout' %}">{{ request.user.username }}<i class="fa fa-sign-out" style="font-size:36px"></i></a></li>
                {% endif %}
            </ul>
        </div>

        <img id="burger-menu" src="{% static 'images/burger-menu.svg' %}" alt="burger-menu">

    </header>

    <section>

        <h2 id="text"><span>Are you ready for</span><br>Hiking Time?</h2>

        <img src="{% static 'images/bird1.png' %}" id="bird1" alt="">
        <img src="{% static 'images/bird2.png' %}" id="bird2" alt="">
        <img src="{% static 'images/forest.png' %}" id="forest" alt="">
        <a href="#sec" id="btn">Get Ready!</a>
        <img src="{% static 'images/rocks.png' %}" id="rocks" alt="">
        <img src="{% static 'images/water.png' %}" id="water" alt="">

    </section>

    <div class="sec" id="sec">
        
        <h2 id="sec_2">Новейшие товары в магазине</h2>

        <div class="cards">
            {% for product in page_obj %}
            <div class="card">
                <img src="{{ product.image.url }}" alt="photo">
                <h3>{{ product }}</h3>
                <p>{{ product.price }}</p>
                <a href="{% url 'detail' product.id %}">
                    <button>Подробнее</button>
                </a>
            </div>
            {% endfor %}
        </div>

        <a href="{% url 'category' shop.slug  %}" style="text-decoration: none;"><button id="btn2">Все товары</button></a>

    </div>

    <footer id="footer">
        <div class="footer-content">
            <div class="contacts">
                <h4>Наши контакты</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
                <p>4</p>
                <p>5</p>
            </div>
            <div class="schedule">
                <h4>График работы</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
            <div class="socials">
                <h4>Социальные сети</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
        </div>
    </footer>

    <script>
        let text = document.getElementById('text');
        let bird1 = document.getElementById('bird1');
        let bird2 = document.getElementById('bird2');
        let btn = document.getElementById('btn');
        let rocks = document.getElementById('rocks');
        let forest = document.getElementById('forest');
        let water = document.getElementById('water');
        let header = document.getElementById('header');

        window.addEventListener('scroll', function(){
            let value = window.scrollY;

            text.style.top = 50 + value * -0.5 + '%';
            bird1.style.top = value * -1.5 + 'px';
            bird1.style.left = value * 2 + 'px';
            bird2.style.top = value * -1.5 + 'px';
            bird2.style.left = value * -5 + 'px';
            btn.style.marginTop = value * 1.5 + 'px';
            rocks.style.top = value * -0.12 + 'px';
            forest.style.top = value * 0.25 + 'px';
            // header.style.top = value * 0.5 + 'px';
        })

        let menuClicked = false;
        const burger_menu = document.getElementById("burger-menu");
        const nav_menu = document.getElementById("nav-menu");

        burger_menu.addEventListener("click", () => {
        if (menuClicked) {
          nav_menu.style.marginRight = "-170px";
          nav_menu.style.display = "none";
        } else {
          nav_menu.style.marginRight = 0;
          nav_menu.style.display = "block";
        }
        menuClicked = !menuClicked;
      });
    </script>

</body>
</html> 

templates/login.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left: 400px; margin-bottom: 50px;">
    <h2 style="margin-top: 125px; margin-bottom: 35px; color: #094b65;">Войдите/Зарегистрируйтесь</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="
    background: #fff;
    width: 100px;
    color: #094b65;
    font-size: 1.2em;
    font-weight: 500;
    letter-spacing: 2px;
    border-radius: 40px;
    margin-bottom: 30px; ">Войти</button>
</form>
    <p style="margin-bottom: 15px; color: #094b65; font-size: 1.5em;">Нет аккаунта? Зарегиструйтесь </p>

    <a href="{% url 'register' %}"><button style="
    background: #fff;
    width: 170px;
    color: #094b65;
    font-size: 1.2em;
    font-weight: 500;
    letter-spacing: 2px;
    border-radius: 40px;">Регистрация</button></a>
</div>
{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin-left: 400px; margin-bottom: 50px;">
    <h2 style="margin-top: 125px; margin-bottom: 20px; color: #094b65;">Оформление заказа</h2>
    <form method="post" style="width: 600px" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
        <h4>Ваши товары:</h4>
        {% for item in cart %}
            {% with product=item.product %}
                <p style="color: #094b65; font-size: 1.2em;">{{ product.title }} --> {{item.quantity}} штуки.</p>
            {% endwith %}
            {% endfor %}
    <button type="submit" style="
    background: #fff;
    width: 230px;
    color: #094b65;
    font-size: 1.2em;
    font-weight: 500;
    letter-spacing: 2px;
    border-radius: 40px;">Оформить заказ</button>
</form>
</div>
{% endblock  %}

templates/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <div class="product">

        <div class="productDetail">

            <div class="product-content">

                <img src="{{ product.image.url }}" alt="">

                <div class="description" >
                    {{ product.description|safe }}
                </div>

            </div>

            <div class="package_info" style="width: 450px;">

                <h4 style="color: #094b65">{{ product.title }}</h4>
                <p>Цена: {{ product.price }} </p>
                <p>Статус: {{ product.get_stock_display }}</p>
                <form action="http://localhost:8000/cart/add/{{ product.id }}/" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" style="width: 170px; background: #fff; color: #094b65; border-radius: 40px;" value="Добавить в корзину">
                </form>


            </div>

        </div>


    </div>
{% endblock %}

templates/productDetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Detail</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header id="header">

        <div id="nav-content">
            <a href="#" class="logo">HikingShop</a>
    
            <form method="get" action="#">
                <input type="text" name="query" id="query" placeholder="Search...">
            </form>
    
            <ul>
                <li><a href="#">Прокат</a></li>
                <li><a href="#">Магазин</a></li>
                <li><a href="#">Корзина</a></li>
                <li><a href="#">Войти</a></li>
            </ul>
        </div>

        <div id="nav-menu">
            <form method="get" action="#">
                <input type="text" name="query" placeholder="Search...">
            </form>
            <ul>
                <li><a href="#" class="active">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Destination</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>

        <img id="burger-menu" src="./media/burger-menu.svg" alt="burger-menu">

    </header>

    <div class="product">

        <div class="productDetail">

            <div class="product-content">

                <img src="./media/photo.jpeg" alt="">

                <div class="description">
                    <p>В этой палатке используются ультралегкий силиконизированный нейлон 20D и дуги из сплава алюминия 7071 - это придает палатке лучшее соотношение прочности и веса.</p>

                    <h3>Характеристики</h3>
                </div>

            </div>

            <div class="package_info">

                <h4>Палатка</h4>
                <p>Цена:</p>
                <button>Добавить в корзину</button>

            </div>

        </div>


    </div>

    <footer id="footer">
        <div class="footer-content">
            <div class="contacts">
                <h4>Наши контакты</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
                <p>4</p>
                <p>5</p>
            </div>
            <div class="schedule">
                <h4>График работы</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
            <div class="socials">
                <h4>Социальные сети</h4>
                <p>1</p>
                <p>2</p>
                <p>3</p>
            </div>
        </div>
    </footer>

</body>
</html> 

templates/registration.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left: 200px; margin-bottom: 50px;">
    <h2 style="margin-top: 125px; margin-bottom: 20px; color: #094b65;">Регистрация</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="
    background: #fff;
    width: 230px;
    color: #094b65;
    font-size: 1.2em;
    font-weight: 500;
    letter-spacing: 2px;
    border-radius: 40px;">Зарегистрироваться</button>
</form>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <h2 id="sec_2" style="margin-top: 100px; margin-left: 140px; color: #094b65; ">Результаты поиска:</h2>
        <div class="cards">
            {% for product in products %}
            <div class="card">
                <img src="{{ product.image.url }}" alt="photo">
                <h3>{{ product }}</h3>
                <p>{{ product.price }}</p>
                <a href="{% url 'detail' product.id %}">
                    <button>Подробнее</button>
                </a>
            </div>
            {% endfor %}
        </div>
{% endblock %}